[bot]
nickname = "Cerith"
username = "Cerith"
realname = "Cerith"
usermode = "iw"
admins = ["nick!user@example.org"]
altnicks = ["Cerith_", "Cerith__"]

[connection]
server = "irc.uni-erlangen.de"
port = 6667

[misc]
prefix = "!"