[bot]
nickname = "Cerith"
username = "Cerith"
realname = "Cerith"
usermode = "iw"
admins = ["nick!user@example.org"]
altnicks = ["Cerith_", "Cerith__"]

[connection]
server_1 = ["irc.uni-erlangen.de", "6667"]
server_2 = ["irc.uni-erlangen.de", "6668"]

[misc]
prefix = "!"

[reactions.hello]
trigger = "hello"
action = "Hello, {nick}!"
occur = 100

